language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r breakaway-webservice *
  - mkdir -p deploy
  - mv breakaway-webservice.zip deploy/breakaway-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIA5HZ4ZIAJAWFJCUHM # AWS_ACCESS_KEY Travis repo setting
    secret_access_key: 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 # AWS_SECRET_KEY Travis repo setting
    bucket: breakaway-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - doydoit@gmail.com